# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ee5c4483-5db3-4727-a65f-35a3511c7dba";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-ee5c4483-5db3-4727-a65f-35a3511c7dba".device = "/dev/disk/by-uuid/ee5c4483-5db3-4727-a65f-35a3511c7dba";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-ee5c4483-5db3-4727-a65f-35a3511c7dba";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-ee5c4483-5db3-4727-a65f-35a3511c7dba";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F730-F43C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
  # Encrypted swap broken
    [ #{ device = "/dev/mapper/luks-cabe29e0-1a02-4fc6-923d-f0a9be4a68a5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
